### ISSUE TITLE
Error: Can't find end of central directory : is this a zip file ?

### ISSUE THREAD

**Issue by Androz2091** [moustacheminer/discord-blocks#11]
Hello, I'm trying to open this file: https://raw.githubusercontent.com/7coil/discord-blocks-bot/81f33ac5eb2d1fdb21bb3bbe786dc7d4e81bbff4/bot/project.xml and I can't. It shows this in the console: 
![Capture d’écran 2020-03-31 à 13 37 29](https://user-images.githubusercontent.com/42497995/78022173-c9e69380-7354-11ea-98dc-c5efffb00028.png)

I would be nice to have more examples of uses of this website 😉

**Comment by 7coil** [comment]
It would be, wouldn't it?

This program only loads .DBL files, so cannot open that file.

**Comment by 7coil** [comment]
Yeah I never updated the example bot.

**Comment by Androz2091** [comment]
@7coil I renamed the .xml file with .dbl and I thought it was going to work 😅 
It would be really nice!

**Comment by 7coil** [comment]
Furthermore, the program has changed so much since that xml example, that its no longer compatible.

Sorry!

**Comment by Androz2091** [comment]
All right. @7coil is it possible to send some other examples? (like how to make an embed?)

**Comment by 7coil** [comment]
I will have to create some

**Comment by Androz2091** [comment]
Nice, thank you!

**Comment by 7coil** [comment]
Working on #9 for examples.
