### ISSUE TITLE
Use new FileReader(); instead of a prompt

### ISSUE THREAD

**Issue by 7coil** [moustacheminer/discord-blocks#2]
This will make it look better.

**Comment by NotWoods** [comment]
To be clear, you want to replace the "Open" button prompt with a file upload? I can take a stab at this!

**Comment by 7coil** [comment]
Yep. Thanks!

**Comment by 7coil** [comment]
https://github.com/moustacheminer/discord-blocks/blob/master/js/discordblocks/index.js

The bit that takes in the XML text is found in line 34 of this file. If you need some XML that goes into there, you can use this

https://raw.githubusercontent.com/moustacheminer/discord-blocks-bot/master/bot/project.xml
