### ISSUE TITLE
Add a donation link.

### ISSUE THREAD

**Issue by binn** [moustacheminer/discord-blocks#7]
This is an amazing project, supporting it is nothing to me.

This is going to help bring many new people into coding, with the proper marketing done.

**Comment by 7coil** [comment]
It's not that amazing, and it's hard to use.
Maybe if I made a better version that was actually worth using, then I would consider doing so

**Comment by 7coil** [comment]
Good news
I'm old enough to implement this now

**Comment by 7coil** [comment]
![image](https://user-images.githubusercontent.com/13886925/56676228-c1ea9200-66b5-11e9-9f4f-d5e4d9e8f302.png)

**Comment by 7coil** [comment]
![image](https://user-images.githubusercontent.com/13886925/78318235-2e277400-755c-11ea-8335-5778d21da27c.png)

There's a sponsor button now!

**Comment by binn** [comment]
<33
